Switch from wget to curl
QubesOS/qubes-core-libvirt pull request #34
Opened 2021-05-12 01:26 UTC by DemiMarie

curl has a better security track record than wget, and on Fedora uses a
better TLS library (OpenSSL instead of GnuTLS).  This change also adds
REPO_PROXY support.

2021-05-14 15:15 UTC, DemiMarie commented
PipelineRetry

2021-05-24 01:29 UTC, marmarek requested changes

2021-05-24 01:29 UTC, marmarek commented on Makefile
> -
This part is not redundant - it is under OS==Windows_NT condition.

2021-05-24 01:29 UTC, marmarek commented on Makefile.common
> +	$(foreach a,$(URL),$(FETCH_CMD) $(call shellquote,$(notdir $a).asc) $(call shellquote,$a.asc) && ):
This is a bit too complex. Maybe split into separate targets for each file? Like it's done in vmm-xen-stubdom-legacy.

2021-05-30 16:04 UTC, marmarek requested changes

2021-05-30 16:04 UTC, marmarek commented on Makefile
> +$(SRC_FILE).asc
Missing colon.

2021-06-01 23:55 UTC, marmarek approved these changes

2021-06-01 23:55 UTC, merged