Builderv2
QubesOS/qubes-core-libvirt pull request #39
Opened 2022-03-25 21:05 UTC by fepitre

2022-03-25 21:13 UTC, fepitre commented
PipelineRetry

2022-04-11 17:38 UTC, fepitre commented
PipelineRetry

2022-07-09 00:54 UTC, marmarek commented
PipelineRetry

2022-07-09 13:27 UTC, marmarek requested changes

2022-07-09 13:27 UTC, marmarek commented on .qubesbuilder
> +    pubkeys: *id001
Better avoid those yaml tricks here (and possibly ban them in the qubes-builder parser).

2022-08-24 12:14 UTC, merged